[package]
name = "sonors"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { version = "1.0.86", features = ["backtrace"] }
argon2 = "0.5.3"
chacha20poly1305 = "0.10.1"
thunderdome = "0.6.1"
walkdir = "2.5.0"

[dev-dependencies]
tempfile = "3.12.0"
